
# Stage 1: Build
FROM node:20 AS build
RUN apt-get update && apt-get install -y --no-install-recommends dumb-init
WORKDIR /usr/src/app
COPY package*.json /usr/src/app/
RUN --mount=type=secret,mode=0644,id=npmrc,target=/usr/src/app/.npmrc npm install \ npm install -g dotenv-cli


# stage 2: Test image
FROM node:20.12.2-bullseye-slim

COPY --from=build /usr/bin/dumb-init /usr/bin/dumb-init
USER node
WORKDIR /usr/src/app

COPY --chown=node:node --from=build /usr/src/app/node_modules /usr/src/app/node_modules

COPY --chown=node:node . /usr/src/app

RUN npx prisma generate
RUN npx prisma migrate dev --name init_test
RUN npx prisma migrate deploy

CMD ["dumb-init", "npm","run" "test"]